In [ ]:
x = 10 (int)
name = "John" (str)
pi = 3.14 (float)
is_true = True (bool)

In [ ]:
#리스트 (list): [1, 2, 3], ['apple', 'banana', 'cherry'] (순서 O, 중복 O, 변경 O)
#튜플 (tuple): (1, 2, 3), ('apple', 'banana', 'cherry') (순서 O, 중복 O, 변경 X)
#딕셔너리 (dictionary): {'name': 'Alice', 'age': 30} (순서 X, 키 중복 X, 변경 O)
#세트 (set): {1, 2, 3}, {'apple', 'banana', 'cherry'} (순서 X, 중복 X, 변경 O)

In [1]:
#제어문(Control Flow)
age = int(input())

if age >= 18:
    print("성인입니다.")
else:
    print("미성년자입니다.")

성인입니다.


In [10]:
fruits = ['apple', 'banana', 'cherry']
for fruit in fruits:
    print(fruit, end=' ')


apple banana cherry 

In [11]:
i = 0
while i < 5:
    print(i, end=' ')
    i += 1

0 1 2 3 4 

In [13]:
#함수(function)
def greet(name):
    print("hello, " + name + "!")

greet("Bob")

hello, Bob!


In [21]:
#활용
def greet(name, age):
    name = str(name)
    age = int(age)
    print(f"hello, {name}{age}!")

greet("Bob", 24)

hello, Bob24!


In [22]:
def add(x,y):
    return x + y

result = add(3, 5)
print(result)

8


In [24]:
num1 = int(input())
num2 = int(input())

def add(num1, num2):
    return num1 + num2

result = add(num1, num2)
print(result)

#print(int(input()) + int(input())) 한줄로 표현도 가능

10


In [25]:
#클래스(Classes)
#데이터(속성)와 기능을 묶어놓은 것(메서드)

class dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
        print(f"{self.name} is a {self.breed} dog.")

    def bark(self):
        print("woof!")

my_dog = dog("Buddy", "Golden Retriever")

Buddy
Woof!


In [33]:
class dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print("woof!")

my_dog = dog("Buddy", "Golden Retriever")
print(my_dog.name, my_dog.breed)
my_dog.bark()

Buddy Golden Retriever
woof!


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

i = 0
for i in range(5):
    i <= 5
    print(i, end=' ')

[1 2 3 4 5]
0 1 2 3 4 

In [54]:
#numpy 라이브러리
import numpy as np

#배열
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#0으로 채우기
brr = np.zeros(5)
print(brr)

#1로 채우기, 2행 3열
crr = np.ones((2,3))
print(crr)

#1-9전까지의 정수로 채우기
drr = np.arange(1,9)
print(drr)

#1-12를 6으로 나누기
err = np.linspace(1,12,6)
print(err)

#단위 행렬
frr = np.eye(3)
print(frr)

#배열 차원 바꾸기 (1차원에서 2차원으로)
reshaped = arr.reshape(5,1)
print(reshaped)

#배열의 합 구하기
print(np.sum(arr))

#배열의 평균구하기(소수점)
print(np.mean(arr))

#배열 이어붙이기
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
combined = np.concatenate((a, b))
print(combined)

#2행 3열로 랜덤 배열 생성
c = np.random.rand(2,3)
print(c)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6 7 8]
[ 1.   3.2  5.4  7.6  9.8 12. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1]
 [2]
 [3]
 [4]
 [5]]
15
3.0
[ 1  2  3  4  5  6  7  8  9 10]
[[0.54168862 0.80455204 0.82087855]
 [0.47619579 0.55084975 0.3260969 ]]


In [63]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])
print(arr)

#배열 연산
arr2 = arr * 2 #배수 표기
print(arr2)

#소수점 3자리까지 표기/ 통계 함수
mean_value = np.mean(arr)
print(f"{mean_value:.3f}")

[1 2 3 4 5]
[ 2  4  6  8 10]
3.000


In [ ]:
#첫 번째 줄은 최소 칼로리
#두 번째 줄은 최대 칼로리
#세 번째 줄은 총 칼로리
#네 번째 줄은 평균 칼로리를 출력합니다.
#(단, 평균 칼로리는 소수점 둘째 자리까지 출력합니다.)

date = np.array(["월", 1950], ["화", 2350], ["수", 1850], ["목", 2200], ["금", 3800], ["토", 2800], ["일", 2000])

cal = (num[1] for num in date)

min_cal = min(cal)
max_cal = max(cal)
total_cal = sum(cal)
mean_cal = np.mean(cal)

In [59]:
#리스트 형식으로 변환값 계산하기
data = [
    ["월", 1950],
    ["화", 2350],
    ["수", 1850],
    ["목", 2200],
    ["금", 3800],
    ["토", 2800],
    ["일", 2000]
]

# 칼로리 값만 추출
calories = [item[1] for item in data]

# 최소, 최대, 총합, 평균 계산
min_cal = min(calories)
max_cal = max(calories)
total_cal = sum(calories)
avg_cal = total_cal / len(calories)

# 출력
print(min_cal)
print(max_cal)
print(total_cal)
print(f"{avg_cal:.2f}")

1850
3800
16950
2421.43


In [58]:
#numpy 라이브러리 활용
import numpy as np

date = np.array([1950, 2350, 1850, 2200, 3800, 2800, 2000])

min_cal = np.min(date)
max_cal = np.max(date)  
total_cal = np.sum(date)    
mean_cal = np.mean(date)

print(min_cal)
print(max_cal)
print(total_cal)
print(f"{mean_cal:.2f}")

1850
3800
16950
2421.43
